[package]
name = "sierra2mlir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
#mlir = { version = "0.1.0", path = "../mlir" }
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo", branch = "main" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
color-eyre = "0.6.2"
melior = { git = "https://github.com/raviqqe/melior", version = "0.3.1" }
