[package]
name = "sierra2mlir"
version = "0.1.0"
edition = "2021"
authors = [
    "Edgar <@edg-l>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "execution"
harness = false

[[bench]]
name = "cairo"
harness = false

[dependencies]
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-alpha.6"}
tracing = "0.1.37"
color-eyre = "0.6.2"
melior-next = { git = "https://github.com/edg-l/melior-next", rev = "e9e68cc70069f93ddd12a9c4cd665a21ed2c6df6"}
itertools = "0.10.5"
regex = "1.7.3"
num-bigint = "0.4.3"
num-traits = "0.2.15"

[dev-dependencies]
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-alpha.6" }
cairo-vm = "0.2.2"
criterion = "0.4.0"
num-bigint = "0.4.3"
num-traits = "0.2.15"
test-case = "3.0.0"
