[package]
name = "mlir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-mlir-sys = { git = "https://github.com/lambdaclass/llvm-mlir-sys", version = "0.1.0" }
