[workspace]
members = [
    "cli",
    "melior-asm",
    "melior-asm-proc",
    "melior-next",
    "sierra2mlir",
    "sierra2mlir-utils",
]

resolver = "2"

[profile.ci-coverage]
inherits = "dev"
opt-level = 3
debug = true
