[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sierra2mlir = { version = "0.1.0", path = "../sierra2mlir" }
clap = { version = "4.1.11", features = ["derive"] }
color-eyre = "0.6.2"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
